name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this if you use a different branch for deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          # Here you would run any build scripts if needed
          # Example: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Root directory containing index.html

  ngrok:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Ngrok
        run: |
          npm install -g @ngrok/ngrok
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }} # Add your Ngrok auth token in GitHub Secrets
          ngrok http 3000
